name: Deploy to Production
on:
  release:
    # type: released
    # A release was published, or a pre-release was changed to a release.
    types: [released]
  # repository_dispatch:
  #   types: [deploy]

jobs:
  deploy:
    name: Deploy to Fly.io and Netlify
    runs-on: ubuntu-latest
    steps:
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - uses: dsaltares/fetch-gh-release-asset@master
        with:
          file: "static-assets.tar.gz"
      - name: Un-tar static assets
        run: tar -xzvf static-assets.tar.gz
      - name: Publish to Netlify
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=target/site --prod
        env:
          NETLIFY_SITE_ID: 92571a12-b93f-4e77-bf4e-744c8ccec4e5
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      - uses: dsaltares/fetch-gh-release-asset@master
        with:
          file: "fly.toml"
      - run: flyctl deploy --image $IMAGE_LABEL
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          IMAGE_LABEL: registry.fly.io/christopherbiscardi:${{github.event.release.name}}
